# Generated by Django 3.1.5 on 2021-01-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
